// packages/ark/masonry/src/react/masonry-item.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/react/factory"
import * as masonry from "@isbatak/zag-masonry"
import { mergeProps } from "@zag-js/react"
import { forwardRef } from "react"
import type { Assign } from "../types"
import { useMasonryContext } from "./use-masonry-context"

export interface MasonryItemBaseProps extends masonry.ItemProps, PolymorphicProps {}
export interface MasonryItemProps extends Assign<HTMLProps<"div">, MasonryItemBaseProps> {}

export const MasonryItem = forwardRef<HTMLDivElement, MasonryItemProps>((props, ref) => {
  const [itemProps, localProps] = masonry.splitItemProps(props)
  const api = useMasonryContext()
  const mergedProps = mergeProps(api.getItemProps(itemProps), localProps)

  return <ark.div {...mergedProps} ref={ref} />
})

MasonryItem.displayName = "MasonryItem"

// packages/ark/masonry/src/svelte/masonry-item.svelte
<script module lang="ts">
  import type { ItemProps } from "@isbatak/zag-masonry"
  import type { Assign } from "../types.js"
  import type { HTMLProps, PolymorphicProps, RefAttribute } from "./types.js"

  export interface MasonryItemBaseProps extends ItemProps, PolymorphicProps<"div">, RefAttribute {}
  export interface MasonryItemProps extends Assign<HTMLProps<"div">, MasonryItemBaseProps> {}
</script>

<script lang="ts">
  import { Ark } from "@ark-ui/svelte"
  import * as masonry from "@isbatak/zag-masonry"
  import { mergeProps } from "@zag-js/svelte"
  import { useMasonryContext } from "./use-masonry-context.js"

  let { ref = $bindable(null), ...props }: MasonryItemProps = $props()
  const [itemProps, localProps] = $derived(masonry.splitItemProps(props))
  const api = useMasonryContext()
  const mergedProps = $derived(mergeProps(api().getItemProps(itemProps), localProps))
</script>

<Ark as="div" bind:ref {...mergedProps} />
