// packages/ui/solid/src/components/loader/loader-overlay.tsx
import { styled } from "@isbatak/ui-solid/jsx"
import type { ComponentProps } from "solid-js"

export const LoaderOverlay = styled("div", {
  base: {
    position: "absolute",
    inset: "0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxSize: "full",
    gap: "2",
  },
})

export type LoaderOverlayProps = ComponentProps<typeof LoaderOverlay>

// packages/panda/ds/src/components/loader/loader-overlay.tsx
"use client"

import { styled } from "@isbatak/panda-ds/jsx"
import type { ComponentProps } from "react"

export const LoaderOverlay = styled("div", {
  base: {
    position: "absolute",
    inset: "0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxSize: "full",
    gap: "2",
  },
})

LoaderOverlay.displayName = "LoaderOverlay"

export type LoaderOverlayProps = ComponentProps<typeof LoaderOverlay>
