// apps/compositions/src/examples/ark/react/wheel-picker-controlled.tsx
"use client"

import { css } from "styled-system/css"
import { wheelPicker as wheelPickerRecipe } from "styled-system/recipes"
import { createWheelPickerCollection, WheelPicker } from "@isbatak/ark-wheel-picker/react"
import { useState } from "react"

const collection = createWheelPickerCollection({
  items: [
    { label: "React", value: "react" },
    { label: "Vue", value: "vue" },
    { label: "Angular", value: "angular" },
    { label: "Svelte", value: "svelte" },
    { label: "Solid", value: "solid" },
  ],
})

const styles = wheelPickerRecipe()

const classes = {
  root: css({ display: "grid", gap: "4" }),
  actions: css({ display: "flex", justifyContent: "center", gap: "2" }),
  button: css({
    px: "3",
    py: "1.5",
    borderWidth: "1px",
    borderRadius: "l2",
    textStyle: "sm",
    cursor: "pointer",
    _hover: { bg: "bg.muted" },
  }),
  output: css({ color: "fg.muted", textStyle: "sm", textAlign: "center" }),
}

export function WheelPickerControlled() {
  const [value, setValue] = useState<string | null>("react")

  return (
    <div className={classes.root}>
      <WheelPicker.Root
        collection={collection}
        value={value}
        onValueChange={(details) => setValue(details.value)}
        className={styles.root}
      >
        <WheelPicker.Label className={styles.label}>Framework</WheelPicker.Label>
        <WheelPicker.Control className={styles.control}>
          <WheelPicker.Viewport className={styles.viewport}>
            <WheelPicker.ItemGroup className={styles.itemGroup}>
              <WheelPicker.Context>
                {(api) =>
                  api.items.map(({ item, index, key }) => (
                    <WheelPicker.Item key={key} item={item} index={index} className={styles.item}>
                      {item.label}
                    </WheelPicker.Item>
                  ))
                }
              </WheelPicker.Context>
            </WheelPicker.ItemGroup>
            <WheelPicker.Highlight className={styles.highlight}>
              <WheelPicker.HighlightItemGroup className={styles.highlightItemGroup}>
                <WheelPicker.Context>
                  {(api) =>
                    api.highlightItems.map(({ item, index, key }) => (
                      <WheelPicker.HighlightItem key={key} item={item} index={index} className={styles.highlightItem}>
                        {item.label}
                      </WheelPicker.HighlightItem>
                    ))
                  }
                </WheelPicker.Context>
              </WheelPicker.HighlightItemGroup>
            </WheelPicker.Highlight>
          </WheelPicker.Viewport>
        </WheelPicker.Control>
      </WheelPicker.Root>
      <div className={classes.actions}>
        <button type="button" className={classes.button} onClick={() => setValue("react")}>
          React
        </button>
        <button type="button" className={classes.button} onClick={() => setValue("svelte")}>
          Svelte
        </button>
      </div>
      <output className={classes.output}>Value: {value}</output>
    </div>
  )
}

// apps/compositions/src/examples/ark/solid/wheel-picker-controlled.tsx
import { css } from "styled-system/css"
import { wheelPicker as wheelPickerRecipe } from "styled-system/recipes"
import { createWheelPickerCollection, WheelPicker } from "@isbatak/ark-wheel-picker/solid"
import { createSignal, Index } from "solid-js"

const collection = createWheelPickerCollection({
  items: [
    { label: "React", value: "react" },
    { label: "Vue", value: "vue" },
    { label: "Angular", value: "angular" },
    { label: "Svelte", value: "svelte" },
    { label: "Solid", value: "solid" },
  ],
})

const styles = wheelPickerRecipe()

const classes = {
  root: css({ display: "grid", gap: "4" }),
  actions: css({ display: "flex", justifyContent: "center", gap: "2" }),
  button: css({
    px: "3",
    py: "1.5",
    borderWidth: "1px",
    borderRadius: "l2",
    textStyle: "sm",
    cursor: "pointer",
    _hover: { bg: "bg.muted" },
  }),
  output: css({ color: "fg.muted", textStyle: "sm", textAlign: "center" }),
}

export function WheelPickerControlled() {
  const [value, setValue] = createSignal<string | null>("react")

  return (
    <div class={classes.root}>
      <WheelPicker.Root
        collection={collection}
        value={value()}
        onValueChange={(details) => setValue(details.value)}
        class={styles.root}
      >
        <WheelPicker.Label class={styles.label}>Framework</WheelPicker.Label>
        <WheelPicker.Control class={styles.control}>
          <WheelPicker.Viewport class={styles.viewport}>
            <WheelPicker.ItemGroup class={styles.itemGroup}>
              <WheelPicker.Context>
                {(api) => (
                  <Index each={api().items}>
                    {(entry) => (
                      <WheelPicker.Item item={entry().item} index={entry().index} class={styles.item}>
                        {entry().item.label}
                      </WheelPicker.Item>
                    )}
                  </Index>
                )}
              </WheelPicker.Context>
            </WheelPicker.ItemGroup>
            <WheelPicker.Highlight class={styles.highlight}>
              <WheelPicker.HighlightItemGroup class={styles.highlightItemGroup}>
                <WheelPicker.Context>
                  {(api) => (
                    <Index each={api().highlightItems}>
                      {(entry) => (
                        <WheelPicker.HighlightItem
                          item={entry().item}
                          index={entry().index}
                          class={styles.highlightItem}
                        >
                          {entry().item.label}
                        </WheelPicker.HighlightItem>
                      )}
                    </Index>
                  )}
                </WheelPicker.Context>
              </WheelPicker.HighlightItemGroup>
            </WheelPicker.Highlight>
          </WheelPicker.Viewport>
        </WheelPicker.Control>
      </WheelPicker.Root>
      <div class={classes.actions}>
        <button type="button" class={classes.button} onClick={() => setValue("react")}>
          React
        </button>
        <button type="button" class={classes.button} onClick={() => setValue("svelte")}>
          Svelte
        </button>
      </div>
      <output class={classes.output}>Value: {value()}</output>
    </div>
  )
}
