// packages/ark/masonry/src/svelte/masonry-root-provider.svelte
<script module lang="ts">
  import type { Assign } from "../types.js"
  import type { HTMLProps, PolymorphicProps, RefAttribute } from "./types.js"
  import type { UseMasonryReturn } from "./use-masonry.svelte.js"

  interface RootProviderProps {
    value: UseMasonryReturn
  }

  export interface MasonryRootProviderBaseProps extends RootProviderProps, PolymorphicProps<"div">, RefAttribute {}
  export interface MasonryRootProviderProps extends Assign<HTMLProps<"div">, MasonryRootProviderBaseProps> {}
</script>

<script lang="ts">
  import { Ark } from "@ark-ui/svelte"
  import { mergeProps } from "@zag-js/svelte"
  import { MasonryProvider } from "./use-masonry-context.js"

  let { ref = $bindable(null), value: api, ...localProps }: MasonryRootProviderProps = $props()
  const mergedProps = $derived(mergeProps(api().getRootProps(), localProps))

  MasonryProvider(() => api())
</script>

<Ark as="div" bind:ref {...mergedProps} />

// packages/ark/masonry/src/solid/masonry-root-provider.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/solid/factory"
import { mergeProps } from "@zag-js/solid"
import { splitProps } from "solid-js"
import type { Assign } from "../types"
import type { UseMasonryReturn } from "./use-masonry"
import { MasonryProvider } from "./use-masonry-context"

interface RootProviderProps {
  value: UseMasonryReturn
}

export interface MasonryRootProviderBaseProps extends RootProviderProps, PolymorphicProps<"div"> {}
export interface MasonryRootProviderProps extends Assign<HTMLProps<"div">, MasonryRootProviderBaseProps> {}

export const MasonryRootProvider = (props: MasonryRootProviderProps) => {
  const [{ value: api }, localProps] = splitProps(props, ["value"])
  const mergedProps = mergeProps(() => api().getRootProps(), localProps)

  return (
    <MasonryProvider value={api}>
      <ark.div {...mergedProps} />
    </MasonryProvider>
  )
}
