// packages/ark/masonry/src/react/masonry-context.tsx
import type { ReactNode } from "react"
import { type UseMasonryContext, useMasonryContext } from "./use-masonry-context"

export interface MasonryContextProps {
  children: (context: UseMasonryContext) => ReactNode
}

export const MasonryContext = (props: MasonryContextProps) => props.children(useMasonryContext())

// packages/ark/masonry/src/solid/masonry-context.tsx
import type { JSX } from "solid-js"
import { type UseMasonryContext, useMasonryContext } from "./use-masonry-context"

export interface MasonryContextProps {
  children: (context: UseMasonryContext) => JSX.Element
}

export const MasonryContext = (props: MasonryContextProps) => props.children(useMasonryContext())
