// packages/ark/masonry/src/react/masonry-root-provider.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/react/factory"
import { mergeProps } from "@zag-js/react"
import { forwardRef } from "react"
import type { Assign } from "../types"
import type { UseMasonryReturn } from "./use-masonry"
import { MasonryProvider } from "./use-masonry-context"

interface RootProviderProps {
  value: UseMasonryReturn
}

export interface MasonryRootProviderBaseProps extends RootProviderProps, PolymorphicProps {}
export interface MasonryRootProviderProps extends Assign<HTMLProps<"div">, MasonryRootProviderBaseProps> {}

export const MasonryRootProvider = forwardRef<HTMLDivElement, MasonryRootProviderProps>((props, ref) => {
  const { value: api, ...localProps } = props
  const mergedProps = mergeProps(api.getRootProps(), localProps)

  return (
    <MasonryProvider value={api}>
      <ark.div {...mergedProps} ref={ref} />
    </MasonryProvider>
  )
})

MasonryRootProvider.displayName = "MasonryRootProvider"

// packages/ark/masonry/src/solid/masonry-root-provider.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/solid/factory"
import { mergeProps } from "@zag-js/solid"
import { splitProps } from "solid-js"
import type { Assign } from "../types"
import type { UseMasonryReturn } from "./use-masonry"
import { MasonryProvider } from "./use-masonry-context"

interface RootProviderProps {
  value: UseMasonryReturn
}

export interface MasonryRootProviderBaseProps extends RootProviderProps, PolymorphicProps<"div"> {}
export interface MasonryRootProviderProps extends Assign<HTMLProps<"div">, MasonryRootProviderBaseProps> {}

export const MasonryRootProvider = (props: MasonryRootProviderProps) => {
  const [{ value: api }, localProps] = splitProps(props, ["value"])
  const mergedProps = mergeProps(() => api().getRootProps(), localProps)

  return (
    <MasonryProvider value={api}>
      <ark.div {...mergedProps} />
    </MasonryProvider>
  )
}
