// packages/ui/react/src/components/spinner/spinner.tsx
"use client"

import { createRecipeContext } from "@isbatak/panda-ds/jsx"
import { spinner } from "@isbatak/panda-ds/recipes"
import type { ComponentProps } from "react"

const { withContext, PropsProvider } = createRecipeContext(spinner)

export const Spinner = withContext("span")
export type SpinnerProps = ComponentProps<typeof Spinner>

export const SpinnerPropsProvider = PropsProvider

// packages/ui/solid/src/components/spinner/spinner.tsx
import { createRecipeContext } from "@isbatak/ui-solid/jsx"
import { spinner } from "@isbatak/panda-ds/recipes"
import type { ComponentProps } from "solid-js"

const { withContext, PropsProvider } = createRecipeContext(spinner)

export const Spinner = withContext("span")
export type SpinnerProps = ComponentProps<typeof Spinner>

export const SpinnerPropsProvider = PropsProvider
