// packages/ark/masonry/src/solid/masonry-item.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/solid/factory"
import * as masonry from "@isbatak/zag-masonry"
import { mergeProps } from "@zag-js/solid"
import { splitProps } from "solid-js"
import type { Assign } from "../types"
import { useMasonryContext } from "./use-masonry-context"

export interface MasonryItemBaseProps extends masonry.ItemProps, PolymorphicProps<"div"> {}
export interface MasonryItemProps extends Assign<HTMLProps<"div">, MasonryItemBaseProps> {}

export const MasonryItem = (props: MasonryItemProps) => {
  const [itemProps, localProps] = splitProps(props, ["value", "span"])
  const api = useMasonryContext()
  const mergedProps = mergeProps(() => api().getItemProps(itemProps), localProps)

  return <ark.div {...mergedProps} />
}

// packages/ark/masonry/src/react/masonry-item.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/react/factory"
import * as masonry from "@isbatak/zag-masonry"
import { mergeProps } from "@zag-js/react"
import { forwardRef } from "react"
import type { Assign } from "../types"
import { useMasonryContext } from "./use-masonry-context"

export interface MasonryItemBaseProps extends masonry.ItemProps, PolymorphicProps {}
export interface MasonryItemProps extends Assign<HTMLProps<"div">, MasonryItemBaseProps> {}

export const MasonryItem = forwardRef<HTMLDivElement, MasonryItemProps>((props, ref) => {
  const [itemProps, localProps] = masonry.splitItemProps(props)
  const api = useMasonryContext()
  const mergedProps = mergeProps(api.getItemProps(itemProps), localProps)

  return <ark.div {...mergedProps} ref={ref} />
})

MasonryItem.displayName = "MasonryItem"
