// packages/ark/masonry/src/svelte/masonry-root.svelte
<script module lang="ts">
  import type { Assign, Optional } from "../types.js"
  import type { HTMLProps, PolymorphicProps, RefAttribute } from "./types.js"
  import type { UseMasonryProps } from "./use-masonry.svelte.js"

  export interface MasonryRootBaseProps extends Optional<UseMasonryProps, "id">, PolymorphicProps<"div">, RefAttribute {}
  export interface MasonryRootProps extends Assign<HTMLProps<"div">, MasonryRootBaseProps> {}
</script>

<script lang="ts">
  import { Ark } from "@ark-ui/svelte"
  import * as masonry from "@isbatak/zag-masonry"
  import { mergeProps } from "@zag-js/svelte"
  import { MasonryProvider } from "./use-masonry-context.js"
  import { useMasonry } from "./use-masonry.svelte.js"

  let { ref = $bindable(null), ...props }: MasonryRootProps = $props()
  const providedId = $props.id()

  const [useMasonryProps, localProps] = $derived(masonry.splitProps(props as Omit<typeof props, "dir">))

  const api = useMasonry(() => ({ ...useMasonryProps, id: useMasonryProps.id ?? providedId }))
  const mergedProps = $derived(mergeProps(api().getRootProps(), localProps))

  MasonryProvider(api)
</script>

<Ark as="div" bind:ref {...mergedProps} />

// packages/ark/masonry/src/react/masonry-root.tsx
import { ark, type HTMLProps, type PolymorphicProps } from "@ark-ui/react/factory"
import * as masonry from "@isbatak/zag-masonry"
import { mergeProps } from "@zag-js/react"
import { forwardRef } from "react"
import type { Assign } from "../types"
import { useMasonry, type UseMasonryProps } from "./use-masonry"
import { MasonryProvider } from "./use-masonry-context"

export interface MasonryRootBaseProps extends UseMasonryProps, PolymorphicProps {}
export interface MasonryRootProps extends Assign<HTMLProps<"div">, MasonryRootBaseProps> {}

export const MasonryRoot = forwardRef<HTMLDivElement, MasonryRootProps>((props, ref) => {
  const [useMasonryProps, localProps] = masonry.splitProps(props as Omit<typeof props, "dir">)
  const api = useMasonry(useMasonryProps)
  const mergedProps = mergeProps(api.getRootProps(), localProps)

  return (
    <MasonryProvider value={api}>
      <ark.div {...mergedProps} ref={ref} />
    </MasonryProvider>
  )
})

MasonryRoot.displayName = "MasonryRoot"
